### ISSUE TITLE
Prepare simple test cases

### ISSUE THREAD

**Issue by guillermoherrero** [Waelazar/Reverse-Vigenere#6]
Prepare a simple test file that contains about three lines with encoded text. This text can be encrypted with the vigenere exercise that was delivered previously as pset.

Using this file can be crucial to determine whether the reverse vigenere algorithm is fully working.

**Comment by diaaaaaa** [comment]
had done 
TestFileD original file  (encrypted with the vigenere) ------>TestFileE
